### ISSUE TITLE
Frontend not working correctly

### ISSUE THREAD

**Issue by aarya-bhatia** [cs240-illinois/sp22_cs240_infinite-maze-shared#10]
I think there is a bug that does not display the new mazes and does not allow user to move further.

**Comment by PeterYR** [comment]
With my changes in #6, the front-end needs to give coordinates with URL parameters to specify where the player is. The coordinates default to (0, 0), so requests to `/generateSegment` (with no URL parameters) will always return the same maze unit.

If you type something like `http://localhost:5000/generateSegment?row=-2&col=2` into your browser it should give you something different.

**Comment by PeterYR** [comment]
I don't know much Javascript, so I haven't been able to modify the front-end to send coordinates. @pcrain any ideas? The front-end just has to send different coordinates in the URL parameters as the player moves to different areas. For example:

- Page loads, player starts at (0, 0): `/generateSegment?row=0&col=0` (can omit the parameters completely as they'll default to 0)
- Player then exits to the east: `/generateSegment?row=0&col=1`
- Player then exits to the south: `/generateSegment?row=-1&col=1`

**Comment by aarya-bhatia** [comment]
You could add the row and col to the URL instead of as query params, to force the frontend to always send the location?

I think we need a system in the front end to do this. In pull request #11 someone has implemented a socket-based protocol to send the MG coordinates. Maybe that is a better idea, rather than sending repeated requests?

**Comment by pcrain** [comment]
I believe I've fixed this issue on the frontend, so closing for now! 🙂
