### ISSUE TITLE
create outer maze border walls even if MG does not provide it

### ISSUE THREAD

**Issue by wadefagen** [cs240-illinois/sp22_cs240_infinite-maze-shared#24]
![image](https://user-images.githubusercontent.com/7505610/166518363-5a239465-99cb-4156-9fc3-5bca2dbb12f3.png)

**Comment by PeterYR** [comment]
@aarya-bhatia set this up in #9, but it didn't work well with multi-block maze segments (it'd add internal walls/exits too), so I removed it in #14. Perhaps we could check whether multiple maze blocks were returned, and only force walls/exits when it's a single block?

**Comment by aarya-bhatia** [comment]
I have a function (Maze::add_boundary) that does exactly this. Like @PeterYR said, it did not work well with multiblock segments. We could work on it to fix the multiblock issue and implement this Issue.

**Comment by PeterYR** [comment]
We could just check if the `extern` key is present in the JSON returned from an MG. If it's not, then it's not a multi-block segment, and we can safely force proper walls/exits. If `extern` **is** present, we can just leave it alone.
