### ISSUE TITLE
Players are rendered as the player color

### ISSUE THREAD

**Issue by wadefagen** [cs240-illinois/sp22_cs240_infinite-maze-shared#32]
Right now it's green/red:

![image](https://user-images.githubusercontent.com/7505610/167046127-a6fe582b-25e2-42e7-a375-7bb2fbd2c944.png)

**Comment by PeterYR** [comment]
If this gets implemented, I think other players should render as dots instead of X's, to distinguish between your own location and others'.

**Comment by wadefagen** [comment]
I just merged https://github.com/cs240-illinois/sp22_cs240_infinite-maze-shared/commit/d5d1af08e66217055a224ce17b6c2b89761f1be0, which included this -- I made the "X" smaller, and a little additional bonus :)
